import type { DomainRoute, DomainsConfig } from './domainRoutesSchema.js';

const CADDY_GLOBAL = `{
\t# HTTP-only homelab; generated by nasmono-home Domains editor
\tauto_https off
}`;

/** Build a Caddyfile from the structured editor model. */
export function generateCaddyfile(config: DomainsConfig): string {
  const blocks = config.routes
    .slice()
    .sort((a, b) => a.hostname.localeCompare(b.hostname))
    .map(
      (route) =>
        `http://${route.hostname} {\n\treverse_proxy ${config.upstreamHost}:${route.port}\n}`,
    );

  return [CADDY_GLOBAL, '', ...blocks, ''].join('\n');
}

/**
 * Pi-hole-style custom DNS lines: `IP hostname` (one per route).
 * Format confirmed against owner DNS file during P1 — adjust if their file differs.
 */
export function generateDnsEntries(config: DomainsConfig): string[] {
  return config.routes
    .slice()
    .sort((a, b) => a.hostname.localeCompare(b.hostname))
    .map((route) => `${config.upstreamHost} ${route.hostname}`);
}

export function generateDnsFile(config: DomainsConfig): string {
  return `${generateDnsEntries(config).join('\n')}\n`;
}

const REVERSE_PROXY_RE = /^\s*reverse_proxy\s+([a-z0-9.:_-]+):(\d+)\s*$/i;

/** Parse IP:port Caddyfile site blocks back into DomainsConfig (round-trip for editor). */
export function parseCaddyfileRoutes(caddyfile: string): DomainsConfig | null {
  const routes: DomainRoute[] = [];
  let upstreamHost: string | null = null;

  const lines = caddyfile.split('\n');
  let currentHost: string | null = null;

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#') || line.startsWith('{') || line === '}') continue;

    const siteMatch = line.match(/^(?:https?:\/\/)?([a-z0-9][-a-z0-9.]*)\s*\{/i);
    if (siteMatch) {
      currentHost = siteMatch[1]!.toLowerCase();
      continue;
    }

    const proxyMatch = line.match(REVERSE_PROXY_RE);
    if (proxyMatch && currentHost) {
      const host = proxyMatch[1]!;
      const port = Number(proxyMatch[2]);
      if (!Number.isInteger(port) || port < 1 || port > 65535) continue;

      // Only accept dotted IPv4 upstreams — container names are out of scope for this editor.
      if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) {
        return null;
      }

      if (upstreamHost == null) upstreamHost = host;
      else if (upstreamHost !== host) return null;

      routes.push({ hostname: currentHost, port });
      currentHost = null;
    }
  }

  if (!upstreamHost || routes.length === 0) return null;

  return { upstreamHost, routes };
}
